services:
  - type: web
    name: pycam
    env: python
    buildCommand: "./build.sh"
    startCommand: ""  # Empty string indicates to use the Procfile
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: pycam_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: pycam.render_settings
      - key: ENVIRONMENT
        value: production
      - key: WEB_CONCURRENCY
        value: 2
      - key: THREADS_PER_WORKER
        value: 1
      - key: GUNICORN_LOG_LEVEL
        value: info
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false  # This needs to be set manually in the Render dashboard
      - key: CLOUDINARY_API_KEY
        sync: false  # This needs to be set manually in the Render dashboard
      - key: CLOUDINARY_API_SECRET
        sync: false  # This needs to be set manually in the Render dashboard

databases:
  - name: pycam_db
    databaseName: pycam
    user: pycam
    plan: free
