services:
  # Web service
  - type: web
    name: pycam
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn pycam.wsgi:application --config=gunicorn_config.py
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: pycam.render_settings
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RENDER
        value: true
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: pycam_db
          property: connectionString

databases:
  - name: pycam_db
    plan: free
    region: oregon
